spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 10
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://${REDIS_HOST:127.0.0.1}:6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 206868531140-2avrv6bqd1migg21ou9u4gjqek43i9qv.apps.googleusercontent.com
            client-secret: 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
            scope: email

logging:
  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
    org.springframework.orm.jpa: ${LOGGING_LEVEL:DEBUG}
    org.springframework.transaction: ${LOGGING_LEVEL:DEBUG}

cloud:
  aws:
    s3:
      bucket: cvs-asset
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MYSQL
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG